name: Python application test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test preprocess with pytest
      run: |
        python -m pytest test/test_preprocess_data.py

    - name: Test features with pytest
      run: |
        python -m pytest test/test_create_features.py

    - name: Test training with pytest
      run: |
        python -m pytest test/test_train_model.py
        
    - name: Test eval with pytest
      run: |
        python -m pytest test/test_train_model.py
        
    - name: Begin execution
      run: |
        python -m pytest test/test_train_model.py
